//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Queries()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int ID { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public int house { get; set; }
        public Nullable<int> apartment { get; set; }
        public int tariff_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
